"""Add title and body to Project model

Revision ID: 96844ccde106
Revises: 7be529cdce9d
Create Date: 2024-10-22 22:55:10.665308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96844ccde106'
down_revision: Union[str, None] = '7be529cdce9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('title', sa.String(), nullable=False))
    op.add_column('project', sa.Column('body', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'body')
    op.drop_column('project', 'title')
    # ### end Alembic commands ###
