name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: jack
          POSTGRES_PASSWORD: password
          POSTGRES_DB: backend
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U jack"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "DB_NAME=backend_test" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_USER=jack" >> $GITHUB_ENV
          echo "DB_PASSWORD=password" >> $GITHUB_ENV

      - name: Create test database
        run: |
          psql -h localhost -U jack -d backend -c "CREATE DATABASE backend_test;"

      - name: Run Alembic migrations
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: backend_test
          DB_USER: jack
          DB_PASSWORD: password
        run: alembic upgrade head

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: backend_test
          DB_USER: jack
          DB_PASSWORD: password
        run: |
          coverage run -m pytest
          coverage report
