name: Deploy to AWS

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: eu-west-1  # Specify your AWS region here

      - name: Build and tag Docker image
        run: |
          docker build -t me-backend .
          docker tag me-backend:latest 047719655736.dkr.ecr.eu-west-1.amazonaws.com/me-backend-repo:latest

      - name: Push Docker image to ECR
        run: |
          docker push 047719655736.dkr.ecr.eu-west-1.amazonaws.com/me-backend-repo:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster me-backend-cluster --service me-backend-service --force-new-deployment --region eu-west-1

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1F6T02STMJGS9 --paths "/*"
